### ISSUE TITLE
required false parameter incorrectly read as true when described in YAML format

### ISSUE THREAD

**Issue by AllanCochrane** [jhthorsen/swagger2#15]
Given YAML like:

```YAML
paths:
  /project_event_types:
    get:
      x-mojo-controller: WebApp::Controller::ProjectEventTypes
      operationId: list
      summary: Project & Event Types
      description: |
        The project & event types endpoint returns information about the projects
        and associated events that have had data uploaded into the database
      parameters:
      - name: project_name
        in: query
        type: string
        required: false
        description: Optional parameter to limit the response to the given project name
```
The project_name parameter is incorrectly pasred as being required because the YAML parser returns the string 'false' and not a boolean value:

```
$ perl -MYAML::Tiny -MData::Dumper -e "print Dumper(YAML::Tiny::Load('required: false'))"
$VAR1 = {
          'required' => 'false'
        };
```

See https://github.com/jhthorsen/swagger2/blob/master/lib/Mojolicious/Plugin/Swagger2.pm#L319
