### ISSUE TITLE
I need to always set SWAGGER_COERCE_VALUES=1

### ISSUE THREAD

**Issue by kberov** [jhthorsen/swagger2#24]
I have the following data:
```
[
  {
    "disabled" => 1,
    "email" => "null\@localhost",
    "first_name" => "Null",
    "group_id" => 1,
    "id" => 1,
    "last_name" => "Null",
    "login_name" => "null"
  },
  {
    "disabled" => 1,
    "email" => "foo\@localhost",
    "first_name" => "Foo",
    "group_id" => 2,
    "id" => 2,
    "last_name" => "Bar",
    "login_name" => "foo"
  },
]
```
I have the following response description:
```
      responses:
        200:
          description: A paged array of users
          headers:
            #This we have to create it before sending the response I think?
            x-next:
              type: string
              description: A link to the next page of responses
          schema: {$ref: "lib/AppName/etc/APIs/definitions.yaml#/definitions/Users"}

```
lib/AppName/etc/APIs/definitions.yaml#/definitions/Users:
```
---
#definitions.yaml: All object definitions go here
definitions:
  User:
    #describe all the required fields
    required:
      - id
      - group_id
      - login_name
      - first_name
      - last_name
      - email
      - disabled
    properties:
      id:
        type: integer
      group_id:
        type: integer
      login_name:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      email:
        type: string
      disabled:
        type: boolean
  Users:
    type: array
    items:
      $ref: User
```
However if I do not set  SWAGGER_COERCE_VALUES, I get the following error:
```
{
  "errors":[
    {"message":"Expected integer - got string.","path":"\/0\/group_id"},
    {"path":"\/0\/id","message":"Expected integer - got string."},
    {"message":"Expected integer - got string.","path":"\/1\/group_id"},
    {"path":"\/1\/id","message":"Expected integer - got string."},
  ],
"valid":false
}
```
Is this expected behavior? I think it is not. My data is "integer".
Looks like the chek here (https://github.com/jhthorsen/swagger2/blob/master/lib/Swagger2/SchemaValidator.pm#L543) is somehow wrong.
Thanks!
